name: "Semantic Title Check"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # https://github.com/commitizen/conventional-commit-types/blob/master/index.json
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            bug
            fix
            hotfix
            chore
            ci
            feat
            doc
            epic
            perf
            refactor
            release
            revert
            test
            security
